version: 2
updates:
- package-ecosystem: github-actions
  directories:
  - /
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  rebase-strategy: auto
  commit-message:
    prefix: '[chore] deps'
  cooldown:
    default-days: 1
    semver-major-days: 7
    semver-minor-days: 3
    semver-patch-days: 1
