name: Steam Gist

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: YouEclipse/steam-box

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Update-gist
        run:  go run ./cmd/box/main.go
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 41cb54b4269afe9a9d1c4d3a3ae00114
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
